"""
Synthetic ES/PT intent corpus — v2 (Factored Hackathon 2026, Team DataMastersGT)

Why v2: the v1 corpus (03_intent_classifier.ipynb) had 144 phrases from ~6 templates per class, and the
train/test split was random over phrases generated from the SAME templates (leakage: the test set
contained near-copies of training phrases). With that setup ML (0.745) did not beat keywords (0.749)
and Portuguese scored 0.657 vs 0.861 Spanish.

v2:
  - ~20 templates per class per language (ES and PT balanced), including "hard" phrasings that do not
    contain the obvious keyword (e.g. "aparece un movimiento raro en mi estado de cuenta").
  - Realistic noise: greetings/closings, lowercase, missing accents, light typos.
  - Every row carries its `template_id`, so evaluation can split BY TEMPLATE (GroupKFold): the model is
    always tested on phrasings it never saw. This is a much harder and more honest test.

The corpus is synthetic and generated by the team (templates drafted with LLM help) — documented as such.
"""

import random
import unicodedata

import pandas as pd

T = {
    "es": {
        "Transactional": [
            "Quiero disputar un cargo de {amount} que no reconozco en mi cuenta",
            "No reconozco una transferencia de {amount} realizada el {date}",
            "Hay un cobro duplicado de {amount} en mi tarjeta de {product}",
            "Mi saldo no refleja un deposito de {amount} que hice {date}",
            "Se me cobro dos veces la misma compra en {merchant}",
            "Veo un retiro de {amount} que yo no hice en el cajero",
            "Necesito que revisen un cargo no reconocido de {amount} en {merchant}",
            "Aparece un movimiento raro en mi estado de cuenta por {amount}",
            "Alguien uso mi tarjeta en {merchant}, yo no hice esa compra",
            "Me debitaron {amount} sin mi autorizacion",
            "Tengo una compra en {merchant} que nunca hice",
            "El cajero no me entrego el dinero pero si me descontaron {amount}",
            "Me llego una notificacion de un pago de {amount} que no fui yo",
            "Quiero desconocer una operacion de {amount} del {date}",
            "Hay un consumo extraño en mi tarjeta, no lo reconozco",
            "Me aparece un pago a {merchant} que no autorice",
            "Pague en {merchant} y me cobraron {amount} de mas",
            "Hicieron una transferencia desde mi cuenta sin mi permiso",
            "No me han devuelto el dinero de una compra cancelada en {merchant}",
            "Quiero reclamar un cobro que no corresponde por {amount}",
        ],
        "Product": [
            "Quiero conocer los beneficios de mi tarjeta de {product}",
            "Cual es la tasa de interes de mi prestamo {product}",
            "Necesito aumentar el limite de mi tarjeta de credito",
            "Como renuevo mi tarjeta que esta por vencer",
            "Quisiera abrir una cuenta de {product} adicional",
            "Que documentos necesito para solicitar un prestamo {product}",
            "Cuanto cuesta la anualidad de la tarjeta",
            "Me pueden explicar como funciona el seguro de mi cuenta",
            "Quiero solicitar una tarjeta adicional para mi esposa",
            "Cual es el plazo maximo para un credito {product}",
            "Como activo mi nueva tarjeta de debito",
            "Quiero saber cuanto me falta por pagar de mi prestamo",
            "Me interesa un credito hipotecario, que requisitos piden",
            "Puedo cambiar la fecha de corte de mi tarjeta",
            "Como hago para domiciliar el pago de mi credito",
            "Quiero reponer mi tarjeta que se daño",
            "Que comision tiene mi cuenta de {product}",
            "Necesito una constancia de mi cuenta de {product}",
        ],
        "Complaint": [
            "Estoy muy molesto con el servicio que recibi en la sucursal",
            "Lleva mas de una semana y nadie resuelve mi caso",
            "El agente fue muy grosero conmigo en la llamada anterior",
            "Esta es la tercera vez que llamo por lo mismo y nadie me ayuda",
            "Me prometieron una solucion y todavia no pasa nada",
            "Quiero presentar una queja formal por el mal servicio recibido",
            "Es una verguenza como atienden en este banco",
            "Espere dos horas en la fila de la sucursal y no me atendieron",
            "Nadie me devuelve las llamadas, estoy harto",
            "Exijo hablar con un supervisor ahora mismo",
            "Pesimo servicio, me tienen dando vueltas desde hace un mes",
            "La ejecutiva me trato muy mal y quiero que quede registrado",
            "Ya no aguanto mas, cada vez que llamo me cuelgan",
            "Me siento ignorado por el banco, nadie me da respuesta",
            "Voy a acudir a la superintendencia si no me resuelven",
            "Me dieron informacion falsa en la sucursal",
            "Que falta de respeto, me cerraron la ventanilla en la cara",
            "Estoy decepcionado con la atencion que he recibido",
        ],
        "Technical": [
            "La aplicacion no me deja iniciar sesion desde {date}",
            "Se me olvido mi clave y la app no me deja recuperarla",
            "La pagina web se cae cada vez que intento pagar",
            "No puedo generar mi estado de cuenta en la app",
            "El token de seguridad no me esta llegando al celular",
            "La app se cierra sola cuando intento hacer una transferencia",
            "Me aparece un error al entrar a la banca en linea",
            "No me llega el codigo de verificacion por SMS",
            "Bloquearon mi usuario despues de tres intentos",
            "La app no carga desde que la actualice",
            "No puedo registrar mi huella en la aplicacion",
            "El sitio dice que mi sesion expiro a cada rato",
            "No me deja descargar el comprobante de pago",
            "La aplicacion se queda congelada en la pantalla de inicio",
            "Cambie de celular y no puedo activar la app",
            "Me sale error 500 cuando entro a mi cuenta en la web",
            "No puedo vincular mi tarjeta a la billetera digital",
            "El chat de la app no responde",
        ],
        "Commercial": [
            "Me interesa conocer las promociones de fin de año",
            "Tienen alguna oferta en creditos {product}",
            "Quiero informacion sobre el programa de puntos y recompensas",
            "Hay descuentos por pagar mi tarjeta antes de tiempo",
            "Me gustaria saber si califico para una tarjeta premium",
            "Que meses sin intereses tienen este mes",
            "Hay alguna promocion para viajar con millas",
            "Como canjeo mis puntos acumulados",
            "Quiero invertir, que opciones de inversion manejan",
            "Tienen cashback en supermercados",
            "Me llego una oferta por correo, es real",
            "Que beneficios tiene el programa de lealtad",
            "Hay tasa preferencial si traslado mi nomina",
            "Quiero saber las ofertas para clientes nuevos",
            "Tienen convenio de descuento en restaurantes",
            "Me interesa un deposito a plazo, que rendimiento dan",
            "Hay alguna campaña de refinanciamiento",
            "Quisiera cotizar un seguro de auto con ustedes",
        ],
        "Retention": [
            "Quiero cancelar mi cuenta, me voy a cambiar de banco",
            "No estoy conforme con las comisiones y quiero cerrar mi tarjeta",
            "Estoy pensando seriamente en cambiarme de banco",
            "Quiero dar de baja todos mis productos con ustedes",
            "Ya no quiero seguir siendo cliente de este banco",
            "Otro banco me ofrece mejores condiciones, me voy",
            "Como cierro mi cuenta definitivamente",
            "Quiero cancelar la tarjeta de credito hoy mismo",
            "Me llevo mi nomina a otro banco",
            "Denme de baja, no quiero nada mas con ustedes",
            "Si no me bajan la anualidad cancelo la tarjeta",
            "Quiero portar mi credito a otra institucion",
            "Estoy cerrando todas mis cuentas aqui",
            "Que necesito para cancelar mi cuenta de {product}",
            "Ya decidi irme, quiero el saldo de cierre",
            "Me cambio a un banco digital, cancelen mi tarjeta",
        ],
    },
    "pt": {
        "Transactional": [
            "Quero contestar uma cobranca de {amount} que nao reconheco na minha conta",
            "Nao reconheco uma transferencia de {amount} feita {date}",
            "Ha uma cobranca duplicada de {amount} no meu cartao de {product}",
            "Meu saldo nao reflete um deposito de {amount} que fiz {date}",
            "Fui cobrado duas vezes pela mesma compra em {merchant}",
            "Vejo uma retirada de {amount} que eu nao fiz no caixa eletronico",
            "Preciso que verifiquem uma cobranca nao reconhecida de {amount} em {merchant}",
            "Apareceu um lancamento estranho no meu extrato de {amount}",
            "Alguem usou meu cartao em {merchant}, eu nao fiz essa compra",
            "Debitaram {amount} sem minha autorizacao",
            "Tenho uma compra em {merchant} que nunca fiz",
            "O caixa nao me entregou o dinheiro mas descontaram {amount}",
            "Recebi uma notificacao de um pagamento de {amount} que nao fui eu",
            "Quero contestar uma operacao de {amount} do dia {date}",
            "Tem um gasto estranho no meu cartao, nao reconheco",
            "Aparece um pagamento para {merchant} que eu nao autorizei",
            "Paguei em {merchant} e me cobraram {amount} a mais",
            "Fizeram um pix da minha conta sem minha permissao",
            "Nao me devolveram o dinheiro de uma compra cancelada em {merchant}",
            "Quero reclamar de uma cobranca indevida de {amount}",
        ],
        "Product": [
            "Quero saber os beneficios do meu cartao {product}",
            "Qual e a taxa de juros do meu emprestimo {product}",
            "Preciso aumentar o limite do meu cartao de credito",
            "Como renovo meu cartao que esta vencendo",
            "Gostaria de abrir uma conta {product} adicional",
            "Quais documentos preciso para pedir um emprestimo {product}",
            "Quanto custa a anuidade do cartao",
            "Podem me explicar como funciona o seguro da minha conta",
            "Quero pedir um cartao adicional para minha esposa",
            "Qual o prazo maximo para um credito {product}",
            "Como ativo meu novo cartao de debito",
            "Quero saber quanto falta pagar do meu emprestimo",
            "Tenho interesse em um financiamento imobiliario, quais os requisitos",
            "Posso mudar a data de vencimento da fatura",
            "Como coloco o pagamento do credito em debito automatico",
            "Quero a segunda via do meu cartao que estragou",
            "Qual a tarifa da minha conta {product}",
            "Preciso de um comprovante da minha conta {product}",
        ],
        "Complaint": [
            "Estou muito insatisfeito com o atendimento que recebi na agencia",
            "Ja faz mais de uma semana e ninguem resolve meu caso",
            "O atendente foi muito mal-educado comigo na ligacao anterior",
            "Esta e a terceira vez que ligo pelo mesmo assunto",
            "Prometeram uma solucao e ate agora nada",
            "Quero registrar uma reclamacao formal pelo mau atendimento",
            "E uma vergonha como atendem neste banco",
            "Esperei duas horas na fila da agencia e nao fui atendido",
            "Ninguem retorna minhas ligacoes, estou cansado",
            "Exijo falar com um supervisor agora",
            "Pessimo servico, estou ha um mes sem resposta",
            "A gerente me tratou muito mal e quero que fique registrado",
            "Nao aguento mais, toda vez que ligo desligam na minha cara",
            "Me sinto ignorado pelo banco, ninguem me responde",
            "Vou ao Banco Central se nao resolverem",
            "Me deram informacao errada na agencia",
            "Que falta de respeito, fecharam o guiche na minha cara",
            "Estou decepcionado com o atendimento",
        ],
        "Technical": [
            "O aplicativo nao me deixa fazer login desde {date}",
            "Esqueci minha senha e o app nao me deixa recupera-la",
            "O site cai toda vez que tento pagar",
            "Nao consigo gerar meu extrato no aplicativo",
            "O token de seguranca nao esta chegando no meu celular",
            "O app fecha sozinho quando tento fazer uma transferencia",
            "Aparece um erro ao entrar no internet banking",
            "Nao chega o codigo de verificacao por SMS",
            "Bloquearam meu usuario depois de tres tentativas",
            "O app nao carrega desde que atualizei",
            "Nao consigo cadastrar minha digital no aplicativo",
            "O site diz que minha sessao expirou toda hora",
            "Nao me deixa baixar o comprovante de pagamento",
            "O aplicativo trava na tela inicial",
            "Troquei de celular e nao consigo ativar o app",
            "Da erro 500 quando entro na minha conta pelo site",
            "Nao consigo vincular meu cartao na carteira digital",
            "O chat do app nao responde",
        ],
        "Commercial": [
            "Tenho interesse em conhecer as promocoes de fim de ano",
            "Voces tem alguma oferta em credito {product}",
            "Quero informacoes sobre o programa de pontos e recompensas",
            "Ha desconto por pagar o cartao antecipado",
            "Eu me qualifico para um cartao premium",
            "Quais parcelamentos sem juros tem este mes",
            "Tem alguma promocao para viajar com milhas",
            "Como troco meus pontos acumulados",
            "Quero investir, quais opcoes de investimento voces tem",
            "Voces tem cashback em supermercados",
            "Recebi uma oferta por email, e verdadeira",
            "Quais beneficios tem o programa de fidelidade",
            "Tem taxa especial se eu trouxer meu salario",
            "Quero saber as ofertas para clientes novos",
            "Tem parceria de desconto em restaurantes",
            "Tenho interesse em um CDB, qual o rendimento",
            "Tem alguma campanha de renegociacao",
            "Gostaria de cotar um seguro de carro com voces",
        ],
        "Retention": [
            "Quero cancelar minha conta, vou mudar de banco",
            "Nao estou satisfeito com as tarifas e quero fechar meu cartao",
            "Estou pensando seriamente em mudar de banco",
            "Quero cancelar todos os meus produtos com voces",
            "Nao quero mais ser cliente deste banco",
            "Outro banco me oferece condicoes melhores, vou sair",
            "Como encerro minha conta definitivamente",
            "Quero cancelar o cartao de credito hoje mesmo",
            "Vou levar meu salario para outro banco",
            "Me descadastrem, nao quero mais nada com voces",
            "Se nao baixarem a anuidade eu cancelo o cartao",
            "Quero fazer a portabilidade do meu credito",
            "Estou encerrando todas as minhas contas aqui",
            "O que preciso para cancelar minha conta {product}",
            "Ja decidi sair, quero o saldo de encerramento",
            "Vou para um banco digital, cancelem meu cartao",
        ],
    },
}

VARS = {
    "es": {"amount": ["$450", "$1,200.00", "$85.50", "3000 pesos", "$620.30", "$150", "$47.99", "250 dolares"],
           "date": ["ayer", "el viernes pasado", "el 3 de junio", "la semana pasada", "el 28 de abril", "hoy"],
           "product": ["ahorros", "credito", "debito", "nomina", "auto", "personal"],
           "merchant": ["un supermercado", "una tienda en linea", "un restaurante", "Amazon", "una gasolinera", "Netflix"]},
    "pt": {"amount": ["R$ 300,00", "R$ 1.500,00", "R$ 89,90", "$120", "R$ 45", "R$ 2.000", "R$ 650,30"],
           "date": ["ontem", "na semana passada", "no dia 3 de junho", "sexta passada", "hoje", "no dia 28 de abril"],
           "product": ["poupanca", "credito pessoal", "debito", "consignado", "corrente"],
           "merchant": ["um supermercado", "uma loja online", "um restaurante", "Mercado Livre", "um posto", "iFood"]},
}

PREFIX = {"es": ["", "", "Hola, ", "Buenas tardes, ", "Buenos dias. ", "Disculpe, ", "Oiga, "],
          "pt": ["", "", "Ola, ", "Boa tarde, ", "Bom dia. ", "Com licenca, ", "Oi, "]}
SUFFIX = {"es": ["", "", ".", ", por favor.", ". Gracias", "?", ", me pueden ayudar?"],
          "pt": ["", "", ".", ", por favor.", ". Obrigado", "?", ", podem me ajudar?"]}

ACCENTS_ES = {"deposito": "depósito", "credito": "crédito", "aplicacion": "aplicación", "pagina": "página",
              "interes de": "interés de", "linea": "línea", "sesion": "sesión", "prestamo": "préstamo"}
ACCENTS_PT = {"nao": "não", "cobranca": "cobrança", "cartao": "cartão", "transferencia": "transferência",
              "credito": "crédito", "sessao": "sessão", "voces": "vocês", "emprestimo": "empréstimo",
              "agencia": "agência", "reclamacao": "reclamação", "promocoes": "promoções", "ligacao": "ligação"}


def _ruido(texto: str, lang: str, rng: random.Random) -> str:
    # half of the rows get proper accents back, the rest stay unaccented (customers type both ways)
    if rng.random() < 0.5:
        for a, b in (ACCENTS_ES if lang == "es" else ACCENTS_PT).items():
            texto = texto.replace(a, b)
    if rng.random() < 0.3:
        texto = texto.lower()
    if rng.random() < 0.15 and len(texto) > 20:  # one-character typo
        i = rng.randrange(5, len(texto) - 5)
        texto = texto[:i] + texto[i + 1:]
    return texto


def generar(n_por_template: int = 6, seed: int = 42) -> pd.DataFrame:
    rng = random.Random(seed)
    rows = []
    for lang, cats in T.items():
        for label, templates in cats.items():
            for j, tpl in enumerate(templates):
                tid = f"{lang}-{label}-{j:02d}"
                for _ in range(n_por_template):
                    txt = tpl.format(**{k: rng.choice(v) for k, v in VARS[lang].items()})
                    pre = rng.choice(PREFIX[lang])
                    if pre:
                        txt = txt[0].lower() + txt[1:]
                    txt = pre + txt + rng.choice(SUFFIX[lang])
                    rows.append({"text": _ruido(txt, lang, rng), "label": label, "lang": lang, "template_id": tid})
    df = pd.DataFrame(rows).drop_duplicates(subset="text").reset_index(drop=True)
    return df


if __name__ == "__main__":
    d = generar()
    print(d.shape)
    print(d.groupby(["lang", "label"]).size().unstack(0))
    print(d.sample(10, random_state=1).to_string())
